#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

function install_and_configure_nginx(){
    sudo apt-get update
    sudo apt-get install -y nginx
    echo "Hello World!" > /var/www/html/index.nginx-debian.html
    sudo nginx -s reload
}

install_and_configure_nginx;
