#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

function install_and_configure_nginx(){
    sudo apt-get update
    sudo apt-get -y install nginx
    echo 'Hello World!' > /var/www/html/index.html
    service nginx start

    sudo sed -i '/server_name localhost;/a\    rewrite ^/redirect_me https://github.com/Itsfoss0 permanent;' /etc/nginx/sites-available/default

}

install_and_configure_nginx;
