#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

function install_and_configure_nginx(){
    sudo apt-get update
    sudo apt-get -y install nginx
    echo 'Hello World!' > /var/www/html/index.html
    sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
    printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        root   /etc/nginx/html;
        index  index.html index.htm;
        location /redirect_me {
            return 301 http://github.com/Itsfoss0;
        }
    }" > /etc/nginx/sites-available/default

    if [[ $(pgrep nginx) ]]; then
        sudo nginx -s reload
    else
        sudo service ngix start
    fi
}
install_and_configure_nginx;
