#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

function install_and_configure_nginx(){
    sudo apt-get update
    sudo apt-get -y install nginx
    echo 'Hello World!' > /var/www/html/index.html
    service nginx start

    sudo sed -i '/server_name localhost;/a\    rewrite ^/redirect_me https://github.com/Itsfoss0 permanent;' /etc/nginx/sites-available/default
    echo "Ceci n'est pas une page" > /var/www/html/404.html
    sudo sed -i '25i\	error_page 404 /404.html;' /etc/nginx/sites-available/default
}

install_and_configure_nginx;
