#!/usr/bin/env bash
#lets get mysql installed on web-01 and web-02

echo "https://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html" > signature.key
sudo apt-key add signature.key
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get  -y update
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*