#!/usr/bin/env bash
#patching up the nginx to listen on port 80
# delete the /etc/nginx/sites-enabled/default and create a symlink

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
