#!/usr/bin/env bash
#patching up the nginx to listen on port 80
function reconfigure_nginx(){
    kill -s 9 "$(pgrep -f nginx)"
    sed -i 's/8080/80' /etc/nginx/sites-enabled/default
    sudo service nginx restart
}
reconfigure_nginx;