#!/usr/bin/env bash
# Configure nginx to listen on port 80 and kill the process ( so the init deamon will flag it as off) :joy: :joy:
udo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo  service nginx restart
pkill -u "$USER", root --oldest
