#!/usr/bin/env bash
# Configure nginx to listen on port 80 and kill the process :joy: :joy:
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx restart
pkill  --oldest
