#!/usr/bin/env bash
#init script for `manage_my_process` process

argument="$1";

function start(){
    ./manage_my_process;
    "pgrep -f manage_my_process" >> "/var/run/my_process.pid";
    echo "manage_my_process started";
}

function stop(){
    kill -9 "$(pgrep -f manage_my_process )";
    rm "/var/run/my_process.pid";
    echo "manage_my_process stopped";
}

function restart(){
    kill -9 "$(pgrep -f manage_my_process)";
    rm "/var/run/my_process.pid";
    ./manage_my_process;
    "pgrep -f manage_my_process" >> "/var/run/my_process.pid";
    echo "manage_my_process restarted";
}

function usage(){
    echo "Usage: manage_my_process {start|stop|restart}";
}


if [ -n "$argument" ]; then
    if [ "$argument" == "start" ]; then 
        start;
    elif [ "$argument" == "stop" ]; then 
        stop;
    elif [ "$argument" == "restart" ]; then 
        restart;
    else
        usage;
    fi
else
    usage;
fi