#!/usr/bin/env bash
#Bad luck from China, Japan and Italy

luck=1;
while [ "$luck" -le 20 ]; do
    case "$luck" in 
        4) 
            echo -e "$luck \nbad luck from China"
            ;;
        9)
            echo -e "$luck \nbad luck from Japan"
            ;;
        17)
            echo -e "$luck \nbad luck from Italy"
            ;;
        *)
            echo "$luck"
            ;;

    esac
    luck=$((luck +1));
done