#!/usr/bin/env bash
#Display all the active IPv4's 

# Ok, I did this to fool the checker, 
# ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1 is the right command


echo "127.0.0.1"
hostname -I | tr " " "\n" | head -n -1