#!/usr/bin/env bash
#with great power, comes great responsibilites. 
#run the `whoami` command as another user

function who_really_am_i(){
    if [[ -z "$1" ]]; then
        echo -e "Which user should we run as?"
    else
        sudo su "$1" -s /bin/bash --command=whoami
    fi

}

who_really_am_i "$1"