#!/usr/bin/env bash
#run nginx as the nginx user and listen on port 8080
kill -s 9 "$(pgrep apache2)"
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo -u nginx -s /bi/bash --command="service nginx restart"
