#!/usr/bin/env bash
#run nginx as the nginx user and listen on port 8080
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
kill -s 9 "(pgrep apache2)"
sudo su -u nginx --command="service nginx start"
